#testAggle

platform :ios, '9.0'


use_frameworks! # this allows you to use import Firebase


pod 'Firebase', '>= 2.5.1'
pod 'JSQMessagesViewController'


#work around fix
#post_install do |installer|
#    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 
#'s/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
#end